### PR TITLE
Add first front-end qunit test and run it with testem

### PR DESCRIPTION
**Pull request by nikolas**
@mcfiredrill PR for you :vhs: 

This adds the first integration test to fortchan12.

To use testem:
- npm install -g testem
- testem

### CODE REVIEW

**Comment by mcfiredrill** [comment]
Does the test pass for you? I get this:
screenshot 2014-04-24 19 08 18

Not sure if thats something I broke or not though.

**Comment by nikolas** [comment]
looks broken for me too i'll see what's going on

**Comment by nikolas** [comment]
@mcfiredrill you need to have the rails server running before running testem. I added this to the commit message.

In `tests.html` we have this line: `<script src="http://localhost:3000/assets/application.js"></script>`

Which is kind of an easy way to get our application's JavaScript..  a nicer way would be to not rely on the rails server here, but use the asset pipeline within testem. I'm still looking in to the solution for that.

**Comment by nikolas** [comment]
^^ maybe a reason to use teaspoon over testem :/

**Comment by mcfiredrill** [comment]
Alright if this is passing I'll merge it and we can switch to another runner later if we want. :vhs:

**Pull request merged**
